name: LiveFleaPrice Fetcher

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt # Install any required Python packages

      - name: Run Python script
        run: python main.py # Replace with the actual command to run your Python script

      - name: Commit and push changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add prices.json tarkovdevprices.json
          git commit -m "Update prices"
          git pull
          git push
